"""add data quality tables

Revision ID: 04c91aad92da
Revises: 02d67d60791c
Create Date: 2026-09-29 12:19:04.245881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04c91aad92da'
down_revision: Union[str, Sequence[str], None] = '02d67d60791c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_checks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('check_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_checks_dataset_id'), 'data_quality_checks', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_data_quality_checks_organization_id'), 'data_quality_checks', ['organization_id'], unique=False)
    op.create_table('data_quality_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('dataset_version_id', sa.UUID(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('total_columns', sa.Integer(), nullable=False),
    sa.Column('missing_values', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('column_statistics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_results_dataset_id'), 'data_quality_results', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_data_quality_results_dataset_version_id'), 'data_quality_results', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_data_quality_results_organization_id'), 'data_quality_results', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_quality_results_organization_id'), table_name='data_quality_results')
    op.drop_index(op.f('ix_data_quality_results_dataset_version_id'), table_name='data_quality_results')
    op.drop_index(op.f('ix_data_quality_results_dataset_id'), table_name='data_quality_results')
    op.drop_table('data_quality_results')
    op.drop_index(op.f('ix_data_quality_checks_organization_id'), table_name='data_quality_checks')
    op.drop_index(op.f('ix_data_quality_checks_dataset_id'), table_name='data_quality_checks')
    op.drop_table('data_quality_checks')
    # ### end Alembic commands ###
